// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxr39ZFojjf5KzD9o3M2opsYbmd1mRd5o',
    appId: '1:148443226194:web:a0f4fa1f35390d0a657f8b',
    messagingSenderId: '148443226194',
    projectId: 'klontong-f79d7',
    authDomain: 'klontong-f79d7.firebaseapp.com',
    storageBucket: 'klontong-f79d7.appspot.com',
    measurementId: 'G-J8H2WEYL2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRjvda6ijiiTl9DnEMSaWFowqYH6auAdI',
    appId: '1:148443226194:android:a5be76b2c20af662657f8b',
    messagingSenderId: '148443226194',
    projectId: 'klontong-f79d7',
    storageBucket: 'klontong-f79d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhf8GZIsxx3nB6fz9OV4AmJcGf4cWaEls',
    appId: '1:148443226194:ios:48d2a94a3cfa11a6657f8b',
    messagingSenderId: '148443226194',
    projectId: 'klontong-f79d7',
    storageBucket: 'klontong-f79d7.appspot.com',
    iosBundleId: 'com.example.klontong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhf8GZIsxx3nB6fz9OV4AmJcGf4cWaEls',
    appId: '1:148443226194:ios:d5bad3adda64dfc0657f8b',
    messagingSenderId: '148443226194',
    projectId: 'klontong-f79d7',
    storageBucket: 'klontong-f79d7.appspot.com',
    iosBundleId: 'com.example.klontong.RunnerTests',
  );
}
